# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-04 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [(b'stamper', '0001_initial'), (b'stamper', '0002_auto_20161122_1243'), (b'stamper', '0003_auto_20161122_1253'), (b'stamper', '0004_auto_20161208_1658'), (b'stamper', '0005_failedtask'), (b'stamper', '0006_webhooklogmanager')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.CharField(max_length=255)),
                ('is_image', models.BooleanField()),
                ('filename', models.CharField(max_length=250)),
                ('is_stored', models.BooleanField()),
                ('done', models.BigIntegerField()),
                ('file_id', models.CharField(max_length=250)),
                ('original_filename', models.CharField(max_length=255)),
                ('is_ready', models.BooleanField()),
                ('total', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageUploadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.CharField(max_length=255)),
                ('is_image', models.BooleanField()),
                ('filename', models.CharField(max_length=250)),
                ('is_stored', models.BooleanField()),
                ('done', models.BigIntegerField()),
                ('file_id', models.CharField(max_length=250)),
                ('original_filename', models.CharField(max_length=255)),
                ('is_ready', models.BooleanField()),
                ('total', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('orientation', models.CharField(max_length=255)),
                ('imgformat', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('geo_location', models.CharField(max_length=255)),
                ('datetime_original', models.DateTimeField()),
                ('dpi', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField()),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.CharField(default='', max_length=4096)),
                ('request_meta', models.CharField(default='', max_length=4096)),
                ('status', models.CharField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1, max_length=250)),
                ('is_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='imageuploadmessage',
            name='webhook_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stamper.WebhookLog'),
        ),
        migrations.AddField(
            model_name='fileuploadmessage',
            name='webhook_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stamper.WebhookLog'),
        ),
        migrations.RemoveField(
            model_name='fileuploadmessage',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='imageuploadmessage',
            name='is_image',
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='dpi',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='geo_location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='imgformat',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='orientation',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='datetime_original',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='fileuploadmessage',
            name='original_file_url',
            field=models.CharField(default=datetime.datetime(2016, 12, 8, 16, 57, 50, 623808, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageuploadmessage',
            name='original_file_url',
            field=models.CharField(default=datetime.datetime(2016, 12, 8, 16, 58, 2, 437475, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=125)),
                ('full_name', models.TextField()),
                ('args', models.TextField(blank=True, null=True)),
                ('kwargs', models.TextField(blank=True, null=True)),
                ('exception_class', models.TextField()),
                ('exception_msg', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(max_length=36)),
                ('failures', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookLogManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
