# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.CharField(max_length=255)),
                ('is_image', models.BooleanField()),
                ('filename', models.CharField(max_length=250)),
                ('is_stored', models.BooleanField()),
                ('done', models.BigIntegerField()),
                ('file_id', models.CharField(max_length=250)),
                ('original_filename', models.CharField(max_length=255)),
                ('is_ready', models.BooleanField()),
                ('total', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageUploadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.CharField(max_length=255)),
                ('is_image', models.BooleanField()),
                ('filename', models.CharField(max_length=250)),
                ('is_stored', models.BooleanField()),
                ('done', models.BigIntegerField()),
                ('file_id', models.CharField(max_length=250)),
                ('original_filename', models.CharField(max_length=255)),
                ('is_ready', models.BooleanField()),
                ('total', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('orientation', models.CharField(max_length=255)),
                ('imgformat', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('geo_location', models.CharField(max_length=255)),
                ('datetime_original', models.DateTimeField()),
                ('dpi', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField()),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.CharField(default='', max_length=4096)),
                ('request_meta', models.CharField(default='', max_length=4096)),
                ('status', models.CharField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1, max_length=250)),
                ('is_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='imageuploadmessage',
            name='webhook_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stamper.WebhookLog'),
        ),
        migrations.AddField(
            model_name='fileuploadmessage',
            name='webhook_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stamper.WebhookLog'),
        ),
    ]
