# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadmessage',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='imageuploadmessage',
            name='is_image',
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='dpi',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='geo_location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='imgformat',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='orientation',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
