# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamper', '0002_auto_20161122_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmessage',
            name='datetime_original',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
