# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamper', '0004_auto_20161208_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=125)),
                ('full_name', models.TextField()),
                ('args', models.TextField(blank=True, null=True)),
                ('kwargs', models.TextField(blank=True, null=True)),
                ('exception_class', models.TextField()),
                ('exception_msg', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(max_length=36)),
                ('failures', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
